namespace: ernstov
malformed-variables:
  defines: runnable
  containers:
    malformed-variables:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: malformed-variables
      port: 8080
      protocol: tcp
